version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:1.19.8-alpine
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf:/etc/nginx/conf.d
